server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
- job_name: oscam
  static_configs:
  - targets:
      - localhost
    labels:
      job: oscam
      __path__: /var/lib/docker/containers/*/*log
  pipeline_stages:
  - json:
      expressions:
        log: log
  - regex:
      expression: ^(?P<is_oscam>(Oscam))-(?P<oscam_port>\d{4,5})[ ].*(?P<is_found>:[ ]found|:[ ]not[ ]found)
      source: log
  - labels:
      is_oscam:
      oscam_port:
      is_found:
  - match:
      selector: '{job="oscam",is_oscam=""}'
      action: drop
