apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscam-020738367216-premier-10011
  labels:
    app: oscam-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oscam-10011
  template:
    metadata:
      labels:
        app: oscam-10011
    spec:
      hostNetwork: true
      containers:
      - image: localhost:5000/oscam-telekarta:v1
        name: oscam-020738367216-premier-10011
        tty: yes
        securityContext:
          privileged: true
        volumeMounts:
        - name: "10011"
          mountPath: /etc/oscam
        - name: tz-moscow
          mountPath: /etc/localtime
      volumes:
        - name: "10011"
          configMap:
            name: "10011"
        - name: tz-moscow
          hostPath:
            path: /usr/share/zoneinfo/Europe/Moscow

