apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscam-32891720289-base-6767
  labels:
    app: oscam-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oscam-server-pod
  template:
    metadata:
      labels:
        app: oscam-server-pod
    spec:
      hostNetwork: true
      containers:
      - env:
        - name: APP_FTDI_SERNUM
          value: "AH00LZ9V"
        - name: APP_PORT
          value: "6767"
        - name: APP_SERVER_IP
          value: "172.17.166.18"
        image: localhost:5000/oscam:v1
        name: oscam-32891720289-base-6767
        tty: yes
        securityContext:
          privileged: true
