apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscam-32891524194-econom-6770
  labels:
    app: oscam-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oscam-server-pod
  template:
    metadata:
      labels:
        app: oscam-server-pod
    spec:
      hostNetwork: true
      containers:
      - env:
        - name: APP_FTDI_SERNUM
          value: "A9CA3W8Z"
        - name: APP_PORT
          value: "6770"
        - name: APP_SERVER_IP
          value: "172.17.166.18"
        image: localhost:5000/oscam:v3
        name: oscam-32891524194-econom-6770
        tty: yes
        securityContext:
          privileged: true

