apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscam-020738367216-premier-10011
  labels:
    app: oscam-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oscam-server-pod
  template:
    metadata:
      labels:
        app: oscam-server-pod
    spec:
      hostNetwork: true
      containers:
      - env:
        - name: APP_FTDI_SERNUM
          value: "AH00LZ9V"
        - name: APP_PORT
          value: "10011"
        - name: APP_SERVER_IP
          value: "172.17.166.18"
        - name: MIN_KEY_NUMBER
          value: "1"
        - name: INFLUX_ADDRESS
          value: "172.17.166.15"
        - name: INFLUX_PORT
          value: "8086"
        - name: LIVE_DELAY
          value: "6"    # 60 сек
        - name: RESTART_DELAY
          value: "12"    # 120 сек
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 60
          periodSeconds: 10
        image: localhost:5000/oscam-telekarta:v6
        name: oscam-020738367216-premier-10011
        tty: yes
        securityContext:
          privileged: true
