#!/bin/sh
touch /tmp/healthy
echo "[global]" > oscam.conf
echo "serverip=$APP_SERVER_IP" >> oscam.conf
echo "logfile=/dev/stdout" >> oscam.conf
echo "[cache]" >> oscam.conf
echo "/dev/null" >> oscam.conf
echo "[newcamd]" >> oscam.conf
echo "port=$APP_PORT@0b00:000000" >> oscam.conf
echo "serverip=$APP_SERVER_IP" >> oscam.conf
echo "key=0102030405060708091011121314" >> oscam.conf
echo "keepalive=1" >> oscam.conf

echo "APP_FTDI_SERNUM=$APP_FTDI_SERNUM"
echo "SERVER_IP=$APP_SERVER_IP"

# echo "{print \"Oscam-$APP_PORT \" \$0}" > awk.conf

for var in $(ls /dev |grep ttyUSB)
do
        if udevadm info -a -n $var |grep $APP_FTDI_SERNUM
        then
                ln -s "/dev/$var" "/dev/ttyUSB128"
		break
        fi
done
# ./oscam -c . |awk -f awk.conf
./oscam -c . |./influx_write $APP_PORT $MIN_KEY_NUMBER $INFLUX_ADDRESS $INFLUX_PORT $LIVE_DELAY $RESTART_DELAY
